# Site settings
title: IT λ…ΈνΈ
description: "IT blog, build with Jekyll."
url: "http://gjchoi.github.io"
author:
  name: "Choi G.J." 
  email: "cyranob82@gmail.com"
  url: "http://gjchoi.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
highlighter : rouge
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
